title: Ravi Bhandia # your name (or website title) here
logo: "images/Ravi_LinkedinPhoto.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm Ravi. Welcome to my website! I'm a recent graduate of UC Berkeley and USC. I am currently deciding on my next chapter in the field of machine learning and data science.
  <br><br>
  Here are a selection of projects that I would like to share with you!
  <br><br>
  <a href="https://www.linkedin.com/in/ravibhandia/">View My LinkedIn Profile</a> 
  <br><br>
  <a href='https://resume.creddle.io/resume/3zr11jigo13'>View My Resume</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-168291379-1 # your Google Analytics tracking ID here
